import type { Metadata } from "next";
import "./globals.css";
import CustomLayout from "./custom-layout";
import StyledComponentsRegistry from "@/lib/registery";

export const metadata: Metadata = {
  title: "Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body suppressHydrationWarning={true}>
        <StyledComponentsRegistry>
          <CustomLayout>{children}</CustomLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
